### ISSUE TITLE
cannot launch it, DBus error

### ISSUE THREAD

**Issue by fedelibre** [dgsasha/remembrance#5]
I installed it for the first time on Fedora 37 and I cannot launch it:

```
$ flatpak run io.github.dgsasha.Remembrance
2023-02-24 17:06:11,198 - Remembrance - INFO - application:connect_to_service - Connected to service
2023-02-24 17:06:11,203 - Remembrance - INFO - application:connect_to_service - Connected to service
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 204, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 81, in do_command_line
    self.do_activate()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 118, in do_activate
    self.check_service_version()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 104, in check_service_version
    loaded_service_version = self.run_service_method(
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 213, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
```

**Comment by fedelibre** [comment]
I cannot reproduce above error when I install Remembrance on my Fedora 37 Silverblue laptop.

I'll try again on my Fedora workstation installation next Monday.

**Comment by fedelibre** [comment]
Now it launches even on my Fedora workstation PC. Maybe the last update on Flathub fixed the problem

**Comment by dgsasha** [comment]
Yeah I made a few changes that I hoped would fix it, good to hear that it did :)

**Comment by dgsasha** [comment]
This isn't actually fixed. On Fedora, the first time you install a Flatpak with a dbus service, the dbus service file is not loaded. Look [here](https://github.com/flatpak/flatpak/issues/3342) for more info, it's probably a bug with Flatpak. Logging out and logging back in fixes the issue.

**Comment by Vaisakhkm2625** [comment]
is there anyway to manually start dbus service??

i too getting this error in fedora 38

```
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: unit failed. (3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: unit failed. (3)

```
