### ISSUE TITLE
[Bug]: Something Went Wrong

### ISSUE THREAD

**Issue by SusieDreemurr** [dgsasha/remembrance#51]
### Package

Flathub

### Distribution

Linux Mint 21.1

### Something Went Wrong

![Screenshot from 2023-07-02 17-49-27](https://github.com/remindersdevs/Reminders/assets/136935928/fe13e87b-7ce5-49e4-aa55-e73eba04ddea)

### To Reproduce

...

### Additional context

I tried uninstalling and reinstalling but I encountered the same error message.

**Comment by icholy** [comment]
Similar error here:

```
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.github.dgsasha.Remembrance.Service2 was not provided by any .service files (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.github.dgsasha.Remembrance.Service2 was not provided by any .service files (2)
```
