### ISSUE TITLE
[Bug]: App crash and can't reopened anymore when setting a repeat frequency

### ISSUE THREAD

**Issue by gremo** [dgsasha/remembrance#59]
### Package

Flathub

### Distribution

Fedora 38

### Describe the bug

App crash and can't be opened anymore, unless reinstall + reboot.

### To Reproduce

Create a new reminder and set the repeat frequency to every 15 minutes

### Logs

```shell
23:11:50 remembrance: TypeError: unsupported operand type(s) for +: 'int' and 'str'
23:11:50 remembrance: TypeError: unsupported operand type(s) for +: 'int' and 'str'
23:11:50 remembrance:     type_name = repeat_frequency + ' ' + _('minutes')
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 272, in get_repeat_label
23:11:50 remembrance:     self.win.get_repeat_label(
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 254, in set_repeat_label
23:11:50 remembrance:     self.set_repeat_label()
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 268, in set_labels
23:11:50 remembrance:     self.set_labels()
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 76, in __init__
23:11:50 remembrance:     reminder = Reminder(
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 640, in display_reminder
23:11:50 remembrance:     self.display_reminder(**reminder)
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 601, in unpack_reminders
23:11:50 remembrance:     self.unpack_reminders(reminders)
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 147, in __init__
23:11:50 remembrance:     self.win = MainWindow(self.page, self)
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 144, in do_activate
23:11:50 remembrance:     self.do_activate()
23:11:50 remembrance:   File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 86, in do_command_line
23:11:50 remembrance: Traceback (most recent call last):
23:11:50 remembrance: 2023-10-02 23:11:50,284 - remembrance - INFO - application:connect_to_service - Connected to service
23:11:50 systemd: Started app-flatpak-io.github.dgsasha.Remembrance-6961.scope.
23:05:34 remembrance: TypeError: unsupported operand type(s) for +: 'int' and 'str'
23:05:34 systemd: Started app-gnome-io.github.dgsasha.Remembrance-5855.scope - Application launched by gnome-shell.
23:05:21 remembrance: TypeError: unsupported operand type(s) for +: 'int' and 'str'
23:05:20 gnome-software: /var/tmp/flatpak-cache-7SZ8B2/io.github.dgsasha.Remembrance-4U1YB2/repo-I8GN96: Pulled app/io.github.dgsasha.Remembrance/x86_64/stable from flathub
23:04:38 sudo:    gremo : TTY=pts/0 ; PWD=/home/gremo ; USER=root ; COMMAND=/usr/bin/flatpak remove io.github.dgsasha.Remembrance.Locale
23:03:42 flatpak: error: app/io.github.dgsasha.Remembrance/x86_64/stable not installed
23:01:45 remembrance: TypeError: unsupported operand type(s) for +: 'int' and 'str'
23:01:30 systemd: Started app-flatpak-io.github.dgsasha.Remembrance-2184.scope.
23:01:12 gnome-software: /var/tmp/flatpak-cache-7SZ8B2/io.github.dgsasha.Remembrance-Y556B2/repo-MCAjJy: Pulled app/io.github.dgsasha.Remembrance/x86_64/stable from flathub
23:00:36 remembrance: TypeError: unsupported operand type(s) for +: 'int' and 'str'
23:00:36 systemd: Started app-gnome-io.github.dgsasha.Remembrance-3753.scope - Application launched by gnome-shell.
23:00:22 remembrance: AttributeError: 'NoneType' object has no attribute 'set_expanded'
22:59:59 systemd: Started app-flatpak-io.github.dgsasha.Remembrance-3555.scope.
22:59:53 remembrance-ser: 2023-10-02 22:59:53,438 - remembrance-service - INFO - application:__init__ - Starting remembrance-service version 4.0
22:59:53 systemd: Started app-flatpak-io.github.dgsasha.Remembrance-2199.scope.
```

**Comment by eldelacajita** [comment]
Same issue here, on EndeavourOS with 45.3, although the traceback looks more like #63.

**Comment by gremo** [comment]
I guess this is not under active development anymore, let's close and forget.
