### ISSUE TITLE
[Bug]: Unsupported operand types - repeat frequency 

### ISSUE THREAD

**Issue by rLoka** [dgsasha/remembrance#63]
### Package

Flathub

### Distribution

Ubuntu 23.10

### Describe the bug

App wont start once you set a reminder to repeat every X minutes

### To Reproduce

1. Run app
2. Set reminder to repeat every X minutes
3. Restart the app
4. App wont start

### Logs

```shell
flatpak run io.github.dgsasha.Remembrance
2023-11-07 09:11:11,107 - remembrance - INFO - application:connect_to_service - Connected to service
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 86, in do_command_line
    self.do_activate()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 144, in do_activate
    self.win = MainWindow(self.page, self)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 147, in __init__
    self.unpack_reminders(reminders)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 601, in unpack_reminders
    self.display_reminder(**reminder)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 640, in display_reminder
    reminder = Reminder(
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 76, in __init__
    self.set_labels()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 268, in set_labels
    self.set_repeat_label()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 254, in set_repeat_label
    self.win.get_repeat_label(
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 272, in get_repeat_label
    type_name = repeat_frequency + ' ' + _('minutes')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by rLoka** [comment]
Duplicate of https://github.com/remindersdevs/Reminders/issues/59
