### ISSUE TITLE
How to reset the app without opening it?

### ISSUE THREAD

**Issue by Froggy232** [dgsasha/remembrance#65]
### Package

Flathub

### Distribution

Fedora Silverblue 39

### Describe the bug

Hi,
First, thanks you a lot for your very useful app!
Everything was working fine, but suddendly the apps crashed and I can't reopen it anymore.
At this point I just want to reset it's database, I have tried to remove the user files folder of the container, but it doesn't solve the problem.
The error message if I try to launch it from a terminal is : 

2023-12-19 17:15:09,297 - remembrance - INFO - application:connect_to_service - Connected to service

(remembrance:2): Gtk-WARNING **: 17:15:09.321: Failed to set text '<span strikethrough='false'>Mises à jour manuelle - Thèmes & UEFI</span>' from markup due to error parsing markup: Erreur à la ligne 1 : L’entité ne se termine pas par un point-virgule ; vous avez probablement utilisé une esperluette sans intention d’écrire une entité — échappez l’esperluette avec &amp;

(remembrance:2): Gtk-WARNING **: 17:15:09.321: Failed to set text '<span strikethrough='false'>Icônes, Firefox & UEFI</span>' from markup due to error parsing markup: Erreur à la ligne 1 : L’entité ne se termine pas par un point-virgule ; vous avez probablement utilisé une esperluette sans intention d’écrire une entité — échappez l’esperluette avec &amp;
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 86, in do_command_line
    self.do_activate()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 144, in do_activate
    self.win = MainWindow(self.page, self)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 147, in __init__
    self.unpack_reminders(reminders)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 601, in unpack_reminders
    self.display_reminder(**reminder)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 640, in display_reminder
    reminder = Reminder(
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 76, in __init__
    self.set_labels()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 268, in set_labels
    self.set_repeat_label()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 254, in set_repeat_label
    self.win.get_repeat_label(
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 277, in get_repeat_label
    type_name = repeat_frequency + ' ' + _('hours')
TypeError: unsupported operand type(s) for +: 'int' and 'str'

Thanks you!

### To Reproduce

I don't know to be honnest, the app just crashed and fail to reopen after that.

### Logs

```shell
2023-12-19 17:15:09,297 - remembrance - INFO - application:connect_to_service - Connected to service

(remembrance:2): Gtk-WARNING **: 17:15:09.321: Failed to set text '<span strikethrough='false'>Mises à jour manuelle - Thèmes & UEFI</span>' from markup due to error parsing markup: Erreur à la ligne 1 : L’entité ne se termine pas par un point-virgule ; vous avez probablement utilisé une esperluette sans intention d’écrire une entité — échappez l’esperluette avec &amp;

(remembrance:2): Gtk-WARNING **: 17:15:09.321: Failed to set text '<span strikethrough='false'>Icônes, Firefox & UEFI</span>' from markup due to error parsing markup: Erreur à la ligne 1 : L’entité ne se termine pas par un point-virgule ; vous avez probablement utilisé une esperluette sans intention d’écrire une entité — échappez l’esperluette avec &amp;
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 86, in do_command_line
    self.do_activate()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 144, in do_activate
    self.win = MainWindow(self.page, self)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 147, in __init__
    self.unpack_reminders(reminders)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 601, in unpack_reminders
    self.display_reminder(**reminder)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 640, in display_reminder
    reminder = Reminder(
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 76, in __init__
    self.set_labels()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 268, in set_labels
    self.set_repeat_label()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 254, in set_repeat_label
    self.win.get_repeat_label(
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 277, in get_repeat_label
    type_name = repeat_frequency + ' ' + _('hours')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by Froggy232** [comment]
App was still running in the background, after stopping it and relaunch it, it seems to work again.
The database seems to get corrupted very easily though.
Thanks for your work!
