### ISSUE TITLE
[Bug]: fails or takes long time to Iopen

### ISSUE THREAD

**Issue by LSeelig** [dgsasha/remembrance#69]
### Package

Flathub

### Distribution

Fedora 39

### Describe the bug

There isn't a clear crash. I will add logs when I get a chance, but it occurs inconsistently.

### To Reproduce

1. Open app

**Comment by marreitin** [comment]
It just crashed for me when trying to start it, same package and distro, but I got the following logs with the notice to report them:
```
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
```
Is it possible this is the same crash? I only got the crash output after trying to open the app for the third time, but it was the first time this happened generally.

**Comment by GraveyardLeprechaun** [comment]
Having the same issue on Linux Mint 21.3 with the same error message. App refuses to start up.

**Comment by LSeelig** [comment]
> Having the same issue on Linux Mint 21.3 with the same error message. App refuses to start up.

The repo owner may be inactive. I say 'may' because they left a note they will be back, but I do not know how long it has been up for. I've been thinking about forking this, but while I might be able to update the interface, I will be useless for fixing sync issues.

What I will recommend is resetting it, then running it in the background from startup from now on. I have not had this issue since then, and it doesn't seem to consume much battery in the background.
