### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by sim6** [dgsasha/remembrance#78]
### Package

Flathub

### Distribution

Nixos 24.11

### Describe the bug

Craches on startup.

### To Reproduce

Install from flathub and create a recurrent reminder.

### Logs

```shell
> flatpak run io.github.dgsasha.Remembrance
2024-12-11 16:00:56,685 - remembrance - INFO - application:connect_to_service - Connected to service
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/remembrance/browser/application.py", line 86, in do_command_line
    self.do_activate()
  File "/app/lib/python3.11/site-packages/remembrance/browser/application.py", line 144, in do_activate
    self.win = MainWindow(self.page, self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/remembrance/browser/main_window.py", line 147, in __init__
    self.unpack_reminders(reminders)
  File "/app/lib/python3.11/site-packages/remembrance/browser/main_window.py", line 601, in unpack_reminders
    self.display_reminder(**reminder)
  File "/app/lib/python3.11/site-packages/remembrance/browser/main_window.py", line 640, in display_reminder
    reminder = Reminder(
               ^^^^^^^^^
  File "/app/lib/python3.11/site-packages/remembrance/browser/reminder.py", line 76, in __init__
    self.set_labels()
  File "/app/lib/python3.11/site-packages/remembrance/browser/reminder.py", line 268, in set_labels
    self.set_repeat_label()
  File "/app/lib/python3.11/site-packages/remembrance/browser/reminder.py", line 254, in set_repeat_label
    self.win.get_repeat_label(
  File "/app/lib/python3.11/site-packages/remembrance/browser/main_window.py", line 272, in get_repeat_label
    type_name = repeat_frequency + ' ' + _('minutes')
                ~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

### Additional context
```
> flatpak info io.github.dgsasha.Remembrance

Reminders - Set reminders for yourself

          ID: io.github.dgsasha.Remembrance
         Ref: app/io.github.dgsasha.Remembrance/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 16.6 MB
     Runtime: org.gnome.Platform/x86_64/46
         Sdk: org.gnome.Sdk/x86_64/46

      Commit: 0fb5401d862d2b325cd232dab6218d9699977254aeabfac65999f99be4a7a789
      Parent: 8871d3506318cccac140e16746914d5dcf9d90c3db8ff81ea7d9e5531aa3ac7d
     Subject: Update Remembrance runtime to 46 (d4d4c025)
        Date: 2024-06-19 07:35:13 +0000
```

**Comment by sim6** [comment]
Ups duplicated of #77, #59, #63, #50 and #36.

**Comment by Getarhubar** [comment]
I'm getting this bug too!
